"""initial schema

Revision ID: 44017205de13
Revises:
Create Date: 2026-08-06 22:54:33.520855

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "44017205de13"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "RUNNING",
                "SCREENING",
                "COMPLETED",
                "PARTIALLY_COMPLETED",
                "FAILED",
                name="runstatus",
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("number_of_stocks", sa.Integer(), nullable=False),
        sa.Column("candidates_found", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stocks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("exchange", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stocks_symbol"), "stocks", ["symbol"], unique=True)
    op.create_table(
        "analysis_run_errors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("analysis_run_id", sa.UUID(), nullable=False),
        sa.Column("stock_symbol", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "screening_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("analysis_run_id", sa.UUID(), nullable=False),
        sa.Column("stock_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CANDIDATE", "NOT_CANDIDATE", "UNKNOWN_DATA_INCOMPLETE", name="screeningstatus"
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("affected_index", sa.Integer(), nullable=True),
        sa.Column("decision_candle_index", sa.Integer(), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("signal_rule_version", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("analysis_run_id", "stock_id", name="uq_screening_result_run_stock"),
    )
    op.create_table(
        "signal_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("screening_result_id", sa.UUID(), nullable=False),
        sa.Column(
            "signal_type",
            sa.Enum("RSI_CROSS", "PRICE_EMA20_BREAKOUT", "EMA5_EMA20_CROSS", name="signaltype"),
            nullable=False,
        ),
        sa.Column("candle_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["screening_result_id"],
            ["screening_results.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("signal_events")
    op.drop_table("screening_results")
    op.drop_table("analysis_run_errors")
    op.drop_index(op.f("ix_stocks_symbol"), table_name="stocks")
    op.drop_table("stocks")
    op.drop_table("analysis_runs")
    # ### end Alembic commands ###
